# Generated by Django 4.2.4 on 2025-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField(max_length=20, null=True)),
                ('lname', models.TextField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.TextField(max_length=20, null=True)),
                ('password', models.TextField(max_length=20, null=True)),
                ('user_profile', models.FileField(null=True, upload_to='images/')),
                ('user_status', models.TextField(default='pending', max_length=50, null=True)),
                ('user_feedback', models.TextField(max_length=1000, null=True)),
                ('messages', models.TextField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'user_register',
            },
        ),
    ]
