# Generated by Django 4.2 on 2026-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('USER', 'User Activity'), ('AI', 'AI Processing'), ('ADMIN', 'Admin Action'), ('SYSTEM', 'System Alert')], max_length=20)),
                ('message', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
